//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerDTO", Namespace="http://schemas.datacontract.org/2004/07/serverProject.BLL")]
    [System.SerializableAttribute()]
    public partial class CustomerDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDTO", Namespace="http://schemas.datacontract.org/2004/07/serverProject.BLL")]
    [System.SerializableAttribute()]
    public partial class OrderDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wpf.ServiceReference1.CustomerDTO CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShabbatParshaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wpf.ServiceReference1.CustomerDTO Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShabbatParsha {
            get {
                return this.ShabbatParshaField;
            }
            set {
                if ((object.ReferenceEquals(this.ShabbatParshaField, value) != true)) {
                    this.ShabbatParshaField = value;
                    this.RaisePropertyChanged("ShabbatParsha");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDetailDTO", Namespace="http://schemas.datacontract.org/2004/07/serverProject.BLL")]
    [System.SerializableAttribute()]
    public partial class OrderDetailDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wpf.ServiceReference1.OrderDTO OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderDetailIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wpf.ServiceReference1.ProductDTO ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wpf.ServiceReference1.OrderDTO Order {
            get {
                return this.OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderField, value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderDetailID {
            get {
                return this.OrderDetailIDField;
            }
            set {
                if ((this.OrderDetailIDField.Equals(value) != true)) {
                    this.OrderDetailIDField = value;
                    this.RaisePropertyChanged("OrderDetailID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wpf.ServiceReference1.ProductDTO Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDTO", Namespace="http://schemas.datacontract.org/2004/07/serverProject.BLL")]
    [System.SerializableAttribute()]
    public partial class ProductDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] imageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryDTO", Namespace="http://schemas.datacontract.org/2004/07/serverProject.BLL")]
    [System.SerializableAttribute()]
    public partial class CategoryDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/num", ReplyAction="http://tempuri.org/IService1/numResponse")]
        int num();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/num", ReplyAction="http://tempuri.org/IService1/numResponse")]
        System.Threading.Tasks.Task<int> numAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/customerCount", ReplyAction="http://tempuri.org/IService1/customerCountResponse")]
        int customerCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/customerCount", ReplyAction="http://tempuri.org/IService1/customerCountResponse")]
        System.Threading.Tasks.Task<int> customerCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomerByPhone", ReplyAction="http://tempuri.org/IService1/GetCustomerByPhoneResponse")]
        wpf.ServiceReference1.CustomerDTO GetCustomerByPhone(string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomerByPhone", ReplyAction="http://tempuri.org/IService1/GetCustomerByPhoneResponse")]
        System.Threading.Tasks.Task<wpf.ServiceReference1.CustomerDTO> GetCustomerByPhoneAsync(string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/orderOpen", ReplyAction="http://tempuri.org/IService1/orderOpenResponse")]
        int orderOpen(string s, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/orderOpen", ReplyAction="http://tempuri.org/IService1/orderOpenResponse")]
        System.Threading.Tasks.Task<int> orderOpenAsync(string s, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetIdOrder", ReplyAction="http://tempuri.org/IService1/GetIdOrderResponse")]
        int GetIdOrder();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetIdOrder", ReplyAction="http://tempuri.org/IService1/GetIdOrderResponse")]
        System.Threading.Tasks.Task<int> GetIdOrderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomers", ReplyAction="http://tempuri.org/IService1/GetCustomersResponse")]
        wpf.ServiceReference1.CustomerDTO[] GetCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomers", ReplyAction="http://tempuri.org/IService1/GetCustomersResponse")]
        System.Threading.Tasks.Task<wpf.ServiceReference1.CustomerDTO[]> GetCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCustomer", ReplyAction="http://tempuri.org/IService1/AddCustomerResponse")]
        bool AddCustomer(wpf.ServiceReference1.CustomerDTO c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCustomer", ReplyAction="http://tempuri.org/IService1/AddCustomerResponse")]
        System.Threading.Tasks.Task<bool> AddCustomerAsync(wpf.ServiceReference1.CustomerDTO c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpDateCustomer", ReplyAction="http://tempuri.org/IService1/UpDateCustomerResponse")]
        bool UpDateCustomer(wpf.ServiceReference1.CustomerDTO customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpDateCustomer", ReplyAction="http://tempuri.org/IService1/UpDateCustomerResponse")]
        System.Threading.Tasks.Task<bool> UpDateCustomerAsync(wpf.ServiceReference1.CustomerDTO customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCustomer", ReplyAction="http://tempuri.org/IService1/DeleteCustomerResponse")]
        bool DeleteCustomer(wpf.ServiceReference1.CustomerDTO c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCustomer", ReplyAction="http://tempuri.org/IService1/DeleteCustomerResponse")]
        System.Threading.Tasks.Task<bool> DeleteCustomerAsync(wpf.ServiceReference1.CustomerDTO c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrder", ReplyAction="http://tempuri.org/IService1/GetOrderResponse")]
        wpf.ServiceReference1.OrderDTO[] GetOrder();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrder", ReplyAction="http://tempuri.org/IService1/GetOrderResponse")]
        System.Threading.Tasks.Task<wpf.ServiceReference1.OrderDTO[]> GetOrderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddOrder", ReplyAction="http://tempuri.org/IService1/AddOrderResponse")]
        bool AddOrder(wpf.ServiceReference1.OrderDTO o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddOrder", ReplyAction="http://tempuri.org/IService1/AddOrderResponse")]
        System.Threading.Tasks.Task<bool> AddOrderAsync(wpf.ServiceReference1.OrderDTO o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpDataOrder", ReplyAction="http://tempuri.org/IService1/UpDataOrderResponse")]
        bool UpDataOrder(wpf.ServiceReference1.OrderDTO order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpDataOrder", ReplyAction="http://tempuri.org/IService1/UpDataOrderResponse")]
        System.Threading.Tasks.Task<bool> UpDataOrderAsync(wpf.ServiceReference1.OrderDTO order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteOrder", ReplyAction="http://tempuri.org/IService1/DeleteOrderResponse")]
        bool DeleteOrder(wpf.ServiceReference1.OrderDTO o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteOrder", ReplyAction="http://tempuri.org/IService1/DeleteOrderResponse")]
        System.Threading.Tasks.Task<bool> DeleteOrderAsync(wpf.ServiceReference1.OrderDTO o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrderDetail", ReplyAction="http://tempuri.org/IService1/GetOrderDetailResponse")]
        wpf.ServiceReference1.OrderDetailDTO[] GetOrderDetail();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrderDetail", ReplyAction="http://tempuri.org/IService1/GetOrderDetailResponse")]
        System.Threading.Tasks.Task<wpf.ServiceReference1.OrderDetailDTO[]> GetOrderDetailAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddOrderDetail", ReplyAction="http://tempuri.org/IService1/AddOrderDetailResponse")]
        bool AddOrderDetail(wpf.ServiceReference1.OrderDetailDTO o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddOrderDetail", ReplyAction="http://tempuri.org/IService1/AddOrderDetailResponse")]
        System.Threading.Tasks.Task<bool> AddOrderDetailAsync(wpf.ServiceReference1.OrderDetailDTO o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpDataOrderDetail", ReplyAction="http://tempuri.org/IService1/UpDataOrderDetailResponse")]
        bool UpDataOrderDetail(wpf.ServiceReference1.OrderDetailDTO o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpDataOrderDetail", ReplyAction="http://tempuri.org/IService1/UpDataOrderDetailResponse")]
        System.Threading.Tasks.Task<bool> UpDataOrderDetailAsync(wpf.ServiceReference1.OrderDetailDTO o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteOrderDetail", ReplyAction="http://tempuri.org/IService1/DeleteOrderDetailResponse")]
        bool DeleteOrderDetail(wpf.ServiceReference1.OrderDetailDTO o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteOrderDetail", ReplyAction="http://tempuri.org/IService1/DeleteOrderDetailResponse")]
        System.Threading.Tasks.Task<bool> DeleteOrderDetailAsync(wpf.ServiceReference1.OrderDetailDTO o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategories", ReplyAction="http://tempuri.org/IService1/GetCategoriesResponse")]
        wpf.ServiceReference1.CategoryDTO[] GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategories", ReplyAction="http://tempuri.org/IService1/GetCategoriesResponse")]
        System.Threading.Tasks.Task<wpf.ServiceReference1.CategoryDTO[]> GetCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCategory", ReplyAction="http://tempuri.org/IService1/AddCategoryResponse")]
        bool AddCategory(wpf.ServiceReference1.CategoryDTO c1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCategory", ReplyAction="http://tempuri.org/IService1/AddCategoryResponse")]
        System.Threading.Tasks.Task<bool> AddCategoryAsync(wpf.ServiceReference1.CategoryDTO c1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpDateCategory", ReplyAction="http://tempuri.org/IService1/UpDateCategoryResponse")]
        bool UpDateCategory(wpf.ServiceReference1.CategoryDTO category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpDateCategory", ReplyAction="http://tempuri.org/IService1/UpDateCategoryResponse")]
        System.Threading.Tasks.Task<bool> UpDateCategoryAsync(wpf.ServiceReference1.CategoryDTO category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCategory", ReplyAction="http://tempuri.org/IService1/DeleteCategoryResponse")]
        bool DeleteCategory(wpf.ServiceReference1.CategoryDTO c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCategory", ReplyAction="http://tempuri.org/IService1/DeleteCategoryResponse")]
        System.Threading.Tasks.Task<bool> DeleteCategoryAsync(wpf.ServiceReference1.CategoryDTO c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProducts", ReplyAction="http://tempuri.org/IService1/GetProductsResponse")]
        wpf.ServiceReference1.ProductDTO[] GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProducts", ReplyAction="http://tempuri.org/IService1/GetProductsResponse")]
        System.Threading.Tasks.Task<wpf.ServiceReference1.ProductDTO[]> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProduct", ReplyAction="http://tempuri.org/IService1/AddProductResponse")]
        bool AddProduct(wpf.ServiceReference1.ProductDTO p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProduct", ReplyAction="http://tempuri.org/IService1/AddProductResponse")]
        System.Threading.Tasks.Task<bool> AddProductAsync(wpf.ServiceReference1.ProductDTO p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpDateProduct", ReplyAction="http://tempuri.org/IService1/UpDateProductResponse")]
        bool UpDateProduct(wpf.ServiceReference1.ProductDTO product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpDateProduct", ReplyAction="http://tempuri.org/IService1/UpDateProductResponse")]
        System.Threading.Tasks.Task<bool> UpDateProductAsync(wpf.ServiceReference1.ProductDTO product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteClient", ReplyAction="http://tempuri.org/IService1/DeleteClientResponse")]
        bool DeleteClient(wpf.ServiceReference1.ProductDTO p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteClient", ReplyAction="http://tempuri.org/IService1/DeleteClientResponse")]
        System.Threading.Tasks.Task<bool> DeleteClientAsync(wpf.ServiceReference1.ProductDTO p);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : wpf.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<wpf.ServiceReference1.IService1>, wpf.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int num() {
            return base.Channel.num();
        }
        
        public System.Threading.Tasks.Task<int> numAsync() {
            return base.Channel.numAsync();
        }
        
        public int customerCount() {
            return base.Channel.customerCount();
        }
        
        public System.Threading.Tasks.Task<int> customerCountAsync() {
            return base.Channel.customerCountAsync();
        }
        
        public wpf.ServiceReference1.CustomerDTO GetCustomerByPhone(string phone) {
            return base.Channel.GetCustomerByPhone(phone);
        }
        
        public System.Threading.Tasks.Task<wpf.ServiceReference1.CustomerDTO> GetCustomerByPhoneAsync(string phone) {
            return base.Channel.GetCustomerByPhoneAsync(phone);
        }
        
        public int orderOpen(string s, int id) {
            return base.Channel.orderOpen(s, id);
        }
        
        public System.Threading.Tasks.Task<int> orderOpenAsync(string s, int id) {
            return base.Channel.orderOpenAsync(s, id);
        }
        
        public int GetIdOrder() {
            return base.Channel.GetIdOrder();
        }
        
        public System.Threading.Tasks.Task<int> GetIdOrderAsync() {
            return base.Channel.GetIdOrderAsync();
        }
        
        public wpf.ServiceReference1.CustomerDTO[] GetCustomers() {
            return base.Channel.GetCustomers();
        }
        
        public System.Threading.Tasks.Task<wpf.ServiceReference1.CustomerDTO[]> GetCustomersAsync() {
            return base.Channel.GetCustomersAsync();
        }
        
        public bool AddCustomer(wpf.ServiceReference1.CustomerDTO c) {
            return base.Channel.AddCustomer(c);
        }
        
        public System.Threading.Tasks.Task<bool> AddCustomerAsync(wpf.ServiceReference1.CustomerDTO c) {
            return base.Channel.AddCustomerAsync(c);
        }
        
        public bool UpDateCustomer(wpf.ServiceReference1.CustomerDTO customer) {
            return base.Channel.UpDateCustomer(customer);
        }
        
        public System.Threading.Tasks.Task<bool> UpDateCustomerAsync(wpf.ServiceReference1.CustomerDTO customer) {
            return base.Channel.UpDateCustomerAsync(customer);
        }
        
        public bool DeleteCustomer(wpf.ServiceReference1.CustomerDTO c) {
            return base.Channel.DeleteCustomer(c);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCustomerAsync(wpf.ServiceReference1.CustomerDTO c) {
            return base.Channel.DeleteCustomerAsync(c);
        }
        
        public wpf.ServiceReference1.OrderDTO[] GetOrder() {
            return base.Channel.GetOrder();
        }
        
        public System.Threading.Tasks.Task<wpf.ServiceReference1.OrderDTO[]> GetOrderAsync() {
            return base.Channel.GetOrderAsync();
        }
        
        public bool AddOrder(wpf.ServiceReference1.OrderDTO o) {
            return base.Channel.AddOrder(o);
        }
        
        public System.Threading.Tasks.Task<bool> AddOrderAsync(wpf.ServiceReference1.OrderDTO o) {
            return base.Channel.AddOrderAsync(o);
        }
        
        public bool UpDataOrder(wpf.ServiceReference1.OrderDTO order) {
            return base.Channel.UpDataOrder(order);
        }
        
        public System.Threading.Tasks.Task<bool> UpDataOrderAsync(wpf.ServiceReference1.OrderDTO order) {
            return base.Channel.UpDataOrderAsync(order);
        }
        
        public bool DeleteOrder(wpf.ServiceReference1.OrderDTO o) {
            return base.Channel.DeleteOrder(o);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteOrderAsync(wpf.ServiceReference1.OrderDTO o) {
            return base.Channel.DeleteOrderAsync(o);
        }
        
        public wpf.ServiceReference1.OrderDetailDTO[] GetOrderDetail() {
            return base.Channel.GetOrderDetail();
        }
        
        public System.Threading.Tasks.Task<wpf.ServiceReference1.OrderDetailDTO[]> GetOrderDetailAsync() {
            return base.Channel.GetOrderDetailAsync();
        }
        
        public bool AddOrderDetail(wpf.ServiceReference1.OrderDetailDTO o) {
            return base.Channel.AddOrderDetail(o);
        }
        
        public System.Threading.Tasks.Task<bool> AddOrderDetailAsync(wpf.ServiceReference1.OrderDetailDTO o) {
            return base.Channel.AddOrderDetailAsync(o);
        }
        
        public bool UpDataOrderDetail(wpf.ServiceReference1.OrderDetailDTO o) {
            return base.Channel.UpDataOrderDetail(o);
        }
        
        public System.Threading.Tasks.Task<bool> UpDataOrderDetailAsync(wpf.ServiceReference1.OrderDetailDTO o) {
            return base.Channel.UpDataOrderDetailAsync(o);
        }
        
        public bool DeleteOrderDetail(wpf.ServiceReference1.OrderDetailDTO o) {
            return base.Channel.DeleteOrderDetail(o);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteOrderDetailAsync(wpf.ServiceReference1.OrderDetailDTO o) {
            return base.Channel.DeleteOrderDetailAsync(o);
        }
        
        public wpf.ServiceReference1.CategoryDTO[] GetCategories() {
            return base.Channel.GetCategories();
        }
        
        public System.Threading.Tasks.Task<wpf.ServiceReference1.CategoryDTO[]> GetCategoriesAsync() {
            return base.Channel.GetCategoriesAsync();
        }
        
        public bool AddCategory(wpf.ServiceReference1.CategoryDTO c1) {
            return base.Channel.AddCategory(c1);
        }
        
        public System.Threading.Tasks.Task<bool> AddCategoryAsync(wpf.ServiceReference1.CategoryDTO c1) {
            return base.Channel.AddCategoryAsync(c1);
        }
        
        public bool UpDateCategory(wpf.ServiceReference1.CategoryDTO category) {
            return base.Channel.UpDateCategory(category);
        }
        
        public System.Threading.Tasks.Task<bool> UpDateCategoryAsync(wpf.ServiceReference1.CategoryDTO category) {
            return base.Channel.UpDateCategoryAsync(category);
        }
        
        public bool DeleteCategory(wpf.ServiceReference1.CategoryDTO c) {
            return base.Channel.DeleteCategory(c);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCategoryAsync(wpf.ServiceReference1.CategoryDTO c) {
            return base.Channel.DeleteCategoryAsync(c);
        }
        
        public wpf.ServiceReference1.ProductDTO[] GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<wpf.ServiceReference1.ProductDTO[]> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
        
        public bool AddProduct(wpf.ServiceReference1.ProductDTO p) {
            return base.Channel.AddProduct(p);
        }
        
        public System.Threading.Tasks.Task<bool> AddProductAsync(wpf.ServiceReference1.ProductDTO p) {
            return base.Channel.AddProductAsync(p);
        }
        
        public bool UpDateProduct(wpf.ServiceReference1.ProductDTO product) {
            return base.Channel.UpDateProduct(product);
        }
        
        public System.Threading.Tasks.Task<bool> UpDateProductAsync(wpf.ServiceReference1.ProductDTO product) {
            return base.Channel.UpDateProductAsync(product);
        }
        
        public bool DeleteClient(wpf.ServiceReference1.ProductDTO p) {
            return base.Channel.DeleteClient(p);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteClientAsync(wpf.ServiceReference1.ProductDTO p) {
            return base.Channel.DeleteClientAsync(p);
        }
    }
}
